const topics=[
 {id:'science',icon:'🔬',name:'Science',desc:'Big ideas about our universe'},
 {id:'technology',icon:'💻',name:'Technology',desc:'How modern tech actually works'},
 {id:'psychology',icon:'🧠',name:'Psychology',desc:'How minds and behavior work'},
 {id:'history',icon:'📜',name:'History',desc:'Moments that shaped our world'},
 {id:'economics',icon:'💰',name:'Economics',desc:'Money, markets and decisions'},
 {id:'space',icon:'🌌',name:'Space',desc:'Explore the cosmos'},
 {id:'biology',icon:'🧬',name:'Biology',desc:'Life from cells to ecosystems'},
 {id:'math',icon:'∑',name:'Mathematics',desc:'Patterns hiding everywhere'}
];
const lessons=[
 {topic:'science',icon:'⚛️',title:'Quantum Computing',tag:'PHYSICS',concept:'Quantum computers use <em>qubits</em> rather than ordinary bits. A normal bit is 0 or 1; a qubit can be described as a combination of states until it is measured.',example:'Imagine a coin spinning in the air. Before it lands, it is not simply heads or tails. A qubit uses a quantum version of this idea called <b>superposition</b>.',question:'Which property lets a qubit represent a combination of states?',options:['Encryption','Superposition','Compilation','Compression'],answer:1},
 {topic:'technology',icon:'🌐',title:'How the Internet Works',tag:'TECHNOLOGY',concept:'The internet is a huge network of connected computers. When you open a website, your device sends packets of data through routers to a server, which sends information back.',example:'Think of a package delivery system. Your message is split into small packages, each routed through a network and reassembled when they arrive.',question:'What do routers primarily do?',options:['Create websites','Route data between networks','Store passwords','Generate electricity'],answer:1},
 {topic:'psychology',icon:'🧠',title:'The Attention Trap',tag:'PSYCHOLOGY',concept:'Your attention is limited. Switching rapidly between tasks feels productive, but each switch carries a mental cost. Focus improves when you reduce competing signals.',example:'Imagine reading a book while someone keeps tapping your shoulder. You can continue reading, but your brain keeps paying a tiny switching cost.',question:'What does rapid task switching generally add?',options:['More focus','A switching cost','More memory','More sleep'],answer:1},
 {topic:'space',icon:'🌌',title:'Black Holes',tag:'ASTRONOMY',concept:'A black hole is a region of spacetime where gravity is so strong that, past the event horizon, nothing—not even light—can escape to the outside.',example:'Picture a waterfall. Far upstream, you can swim away. Past a certain point near the drop, the current becomes impossible to overcome. That boundary is a rough analogy for an event horizon.',question:'What is the event horizon?',options:['A black hole’s surface','A boundary beyond which escape is impossible','A visible star','The center of a galaxy'],answer:1},
 {topic:'biology',icon:'🧬',title:'DNA',tag:'BIOLOGY',concept:'DNA is a molecule that stores biological instructions. Sections of DNA called genes can provide information used by cells to build proteins and regulate processes.',example:'Think of DNA as a huge library. Genes are like individual recipes, while the cell has machinery that reads and uses those instructions.',question:'What does DNA primarily store?',options:['Heat','Biological information','Electricity','Oxygen'],answer:1},
 {topic:'science',icon:'🌈',title:'Why Is the Sky Blue?',tag:'PHYSICS',concept:'Sunlight contains many wavelengths. Earth’s atmosphere scatters shorter blue wavelengths more strongly than longer red wavelengths, making blue light arrive at our eyes from many directions.',example:'Shine a flashlight through a misty room: tiny particles scatter light sideways. Earth’s air does something similar, with blue light scattering more strongly.',question:'Which color is scattered more strongly by Earth’s atmosphere?',options:['Red','Blue','Infrared','Black'],answer:1},
 {topic:'technology',icon:'🔐',title:'Public-Key Cryptography',tag:'CYBERSECURITY',concept:'Public-key cryptography uses a pair of mathematically related keys. A public key can be shared openly, while a private key is kept secret.',example:'Imagine a mailbox with a slot anyone can use to put in a letter, but only the owner has the key to open it and retrieve what is inside.',question:'Which key should normally remain secret?',options:['Public key','Private key','Browser key','Router key'],answer:1},
 {topic:'psychology',icon:'🧩',title:'Confirmation Bias',tag:'PSYCHOLOGY',concept:'Confirmation bias is the tendency to notice, interpret, or remember information in ways that support beliefs we already hold.',example:'If you believe a certain brand is unreliable, you may remember every failure while overlooking the many times it worked normally.',question:'What does confirmation bias tend to favor?',options:['Evidence that challenges beliefs','Information consistent with existing beliefs','Random information','Perfectly neutral memories'],answer:1},
 {topic:'history',icon:'🏛️',title:'The Printing Press',tag:'HISTORY',concept:'Movable-type printing made it much faster and cheaper to reproduce texts in large quantities. This helped information circulate more widely in Europe.',example:'Before mass printing, copying a book could take a long time by hand. A press allowed many similar pages to be produced much more efficiently.',question:'What did printing primarily make easier?',options:['Mass reproduction of texts','Building ships','Predicting weather','Generating electricity'],answer:0},
 {topic:'economics',icon:'📈',title:'Supply and Demand',tag:'ECONOMICS',concept:'Supply describes how much sellers are willing to offer, while demand describes how much buyers want at different prices. Their interaction helps determine market prices.',example:'If concert tickets are scarce but many people want them, buyers may compete for the limited supply, pushing the market price upward.',question:'What can happen when demand rises while supply stays fixed?',options:['Price pressure can rise','Demand disappears','Supply becomes infinite','Money stops existing'],answer:0},
 {topic:'space',icon:'🪐',title:'Why Planets Orbit',tag:'ASTRONOMY',concept:'A planet’s forward motion combines with the Sun’s gravitational pull. Instead of flying straight away, the planet continuously falls toward the Sun while moving sideways.',example:'Swing a ball on a string: the ball wants to travel straight, while the string pulls it inward. The combination creates a curved path.',question:'What keeps a planet bound to the Sun?',options:['Gravity','Sound','Magnetism alone','Clouds'],answer:0},
 {topic:'biology',icon:'🫀',title:'How Your Heart Beats',tag:'BIOLOGY',concept:'The heart is a muscular pump. Electrical signals coordinate contractions so blood is pushed through the chambers and into the lungs and body.',example:'Think of a two-stage pump: one side sends blood toward the lungs, while the other sends oxygen-rich blood around the body.',question:'What coordinates the heart’s contractions?',options:['Electrical signals','Bones','Hair follicles','Stomach acid'],answer:0},
 {topic:'math',icon:'∞',title:'Infinity',tag:'MATHEMATICS',concept:'Infinity is not an ordinary number. It describes something without an upper bound, and different infinite sets can have surprising relationships in mathematics.',example:'The counting numbers never end: 1, 2, 3, 4, and so on. There is always another number.',question:'Is infinity an ordinary finite number?',options:['Yes','No','Only on weekends','Only in geometry'],answer:1}
];
const defaultState={xp:0,lessons:0,streak:0,completed:[],recent:[],lastDay:null,dailyDate:null,dailyDone:0,topicScores:{},wrong:[]};
let state=loadState(),queue=[],lessonIndex=0,phase=0,answered=false,timer=null,feedMode='all';
function loadState(){try{return {...defaultState,...JSON.parse(localStorage.getItem('omu-state')||'{}')}}catch{return {...defaultState}}}
function save(){localStorage.setItem('omu-state',JSON.stringify(state));updateStats()}
function today(){return new Date().toISOString().slice(0,10)}
function resetDailySafe(){if(state.dailyDate!==today()){state.dailyDate=today();state.dailyDone=0;localStorage.setItem('omu-state',JSON.stringify(state))}}
function updateStats(){resetDailySafe();['xpStat','profileXP'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=state.xp});['streakStat','profileStreak'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=state.streak});const lessonsEl=document.getElementById('profileLessons');if(lessonsEl)lessonsEl.textContent=state.lessons;const pct=Math.min(100,Math.round(state.completed.length/lessons.length*100));const p=document.getElementById('progressPercent'),bar=document.getElementById('progressBar');if(p)p.textContent=pct+'%';if(bar)bar.style.width=pct+'%';renderRecent();updateJourney();const d=document.getElementById('dailyProgress');if(d)d.textContent=`${Math.min(state.dailyDone,5)}/5 complete`}
function renderTopics(){const grid=document.getElementById('topicGrid');if(!grid)return;grid.innerHTML=topics.map(t=>`<button class="topic-card" data-topic="${t.id}"><div class="topic-icon">${t.icon}</div><h3>${t.name}</h3><p>${t.desc}</p></button>`).join('');document.querySelectorAll('.topic-card').forEach(b=>b.onclick=()=>startTopic(b.dataset.topic))}
function renderRecent(){const e=document.getElementById('recentList');if(!e)return;if(!state.recent.length){e.innerHTML='<div class="recent-item"><span>No lessons yet.</span><b>Start learning →</b></div>';return}e.innerHTML=state.recent.slice(0,6).map(x=>`<div class="recent-item"><b>${x.icon} ${x.title}</b><span>+${x.xp} XP</span></div>`).join('')}
function updateJourney(){const title=document.getElementById('journeyTitle'),text=document.getElementById('journeyText');if(!title||!text)return;if(state.lessons){title.textContent='Keep your streak alive.';text.textContent=`You've learned ${state.lessons} topic${state.lessons===1?'':'s'}. ${state.dailyDone<5?`${5-state.dailyDone} Daily 5 lesson${5-state.dailyDone===1?'':'s'} left.`:'Daily 5 complete!'}`}}
function showView(id){document.querySelectorAll('main>section').forEach(s=>s.classList.add('hidden'));const target=document.getElementById(id);if(target)target.classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.nav===id));window.scrollTo({top:0,behavior:'smooth'})}
function getRecommended(){const unseen=lessons.filter(l=>!state.completed.includes(l.title));const weak=Object.entries(state.topicScores).sort((a,b)=>(a[1]||0)-(b[1]||0)).map(x=>x[0]);const prioritized=[...unseen].sort((a,b)=>{const aw=weak.indexOf(a.topic),bw=weak.indexOf(b.topic);return(aw<0?99:aw)-(bw<0?99:bw)});return prioritized.length?prioritized:[...lessons].sort(()=>Math.random()-.5)}
function startTopic(topic){queue=lessons.filter(l=>l.topic===topic);feedMode='topic';openLesson()}
function startLearning(){queue=getRecommended();feedMode='all';openLesson()}
function startDaily(){resetDailySafe();queue=[...lessons].sort((a,b)=>(state.completed.includes(a.title)?1:0)-(state.completed.includes(b.title)?1:0)).slice(0,5);feedMode='daily';openLesson()}
function reviewMistakes(){const r=lessons.filter(l=>state.wrong.includes(l.title));queue=r.length?r:[...lessons];feedMode='review';openLesson()}
function openLesson(){if(!queue.length)queue=[...lessons];lessonIndex=0;phase=0;answered=false;const o=document.getElementById('lessonOverlay');if(o)o.classList.remove('hidden');document.body.style.overflow='hidden';renderLesson()}
function renderLesson(){clearInterval(timer);const l=queue[lessonIndex%queue.length],c=document.getElementById('lessonContent');const count=document.getElementById('lessonCount'),progress=document.getElementById('lessonProgress');if(count)count.textContent=`${lessonIndex+1} / ${queue.length}`;if(progress)progress.style.width=(lessonIndex/queue.length*100)+'%';if(!c)return;if(phase===0){c.innerHTML=`<span class="lesson-kicker">${l.tag} · 30 SEC</span><h2>${l.icon} ${l.title}</h2><p>${l.concept}</p>`;setTimer(30,'30 sec')}else if(phase===1){c.innerHTML=`<span class="lesson-kicker">MAKE IT CLICK · 20 SEC</span><h2>Think of it <em>like this.</em></h2><div class="example-box"><strong>REAL-WORLD EXAMPLE</strong><div>${l.example}</div></div>`;setTimer(20,'20 sec')}else{c.innerHTML=`<span class="lesson-kicker">RECALL · 10 SEC</span><h2>Quick <em>test.</em></h2><p>${l.question}</p><div class="quiz-options">${l.options.map((o,i)=>`<button class="quiz-option" data-i="${i}">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div>`;document.querySelectorAll('.quiz-option').forEach(b=>b.onclick=()=>answer(Number(b.dataset.i)));document.getElementById('timerLabel').textContent='10 sec'}document.getElementById('lessonNext').textContent=phase<2?'Continue →':'Next topic →'}
function setTimer(seconds,label){let left=seconds,e=document.getElementById('timerLabel');if(e)e.textContent=label;timer=setInterval(()=>{left--;if(e)e.textContent=left+' sec';if(left<=0){clearInterval(timer);advancePhase()}},1000)}
function advancePhase(){if(phase<2){phase++;renderLesson()}else nextLesson()}
function answer(i){if(answered)return;answered=true;clearInterval(timer);const l=queue[lessonIndex%queue.length],buttons=document.querySelectorAll('.quiz-option');buttons.forEach((b,n)=>{if(n===l.answer)b.classList.add('correct');if(n===i&&i!==l.answer)b.classList.add('wrong')});const correct=i===l.answer;if(correct){state.xp+=10;showToast('+10 XP · Correct!')}else{if(!state.wrong.includes(l.title))state.wrong.push(l.title);showToast('Not quite · added to review')}state.topicScores[l.topic]=(state.topicScores[l.topic]||0)+(correct?1:-1);completeLesson(l,correct);document.getElementById('lessonNext').textContent='Next topic →'}
function completeLesson(l,correct){if(state.completed.includes(l.title))return;state.completed.push(l.title);state.lessons++;state.recent.unshift({title:l.title,icon:l.icon,xp:correct?10:0});state.recent=state.recent.slice(0,10);if(feedMode==='daily')state.dailyDone=Math.min(5,state.dailyDone+1);if(state.streak===0)state.streak=1;else if(state.lastDay!==today())state.streak++;state.lastDay=today();save()}
function nextLesson(){lessonIndex++;phase=0;answered=false;if(feedMode==='daily'&&lessonIndex>=queue.length){showToast('🎉 Daily 5 complete!');closeLesson();return}if(lessonIndex>=queue.length){queue=getRecommended();lessonIndex=0}renderLesson()}
function closeLesson(){clearInterval(timer);const o=document.getElementById('lessonOverlay');if(o)o.classList.add('hidden');document.body.style.overflow='';updateStats()}
function showToast(text){const t=document.getElementById('toast');if(!t)return;t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function handleSwipe(){let sy=0;const shell=document.querySelector('.lesson-shell');if(!shell)return;shell.addEventListener('touchstart',e=>sy=e.changedTouches[0].screenY,{passive:true});shell.addEventListener('touchend',e=>{const dy=e.changedTouches[0].screenY-sy;if(Math.abs(dy)>60){if(dy<0)advancePhase();else if(phase>0){phase--;renderLesson()}}},{passive:true})}
const bind=(id,event,fn)=>{const e=document.getElementById(id);if(e)e.addEventListener(event,fn)};
bind('startBtn','click',startLearning);bind('continueBtn','click',startLearning);bind('exploreBtn','click',()=>document.getElementById('topicsView')?.scrollIntoView({behavior:'smooth'}));bind('allTopicsBtn','click',()=>document.getElementById('topicsView')?.scrollIntoView({behavior:'smooth'}));bind('closeLesson','click',closeLesson);bind('lessonNext','click',advancePhase);bind('profileBtn','click',()=>showView('profileView'));bind('profileBack','click',()=>showView('homeView'));bind('homeBtn','click',()=>showView('homeView'));bind('searchBtn','click',()=>showToast('Tip: use Explore to jump into a topic.'));document.querySelectorAll('.nav-item').forEach(n=>n.addEventListener('click',()=>showView(n.dataset.nav)));bind('dailyBtn','click',startDaily);bind('reviewBtn','click',reviewMistakes);renderTopics();handleSwipe();updateStats();
