const topics=[
 {id:'science',icon:'🔬',name:'Science',desc:'Big ideas about our universe'},
 {id:'technology',icon:'💻',name:'Technology',desc:'How modern tech actually works'},
 {id:'psychology',icon:'🧠',name:'Psychology',desc:'How minds and behavior work'},
 {id:'history',icon:'📜',name:'History',desc:'Moments that shaped our world'},
 {id:'economics',icon:'💰',name:'Economics',desc:'Money, markets and decisions'},
 {id:'space',icon:'🌌',name:'Space',desc:'Explore the cosmos'},
 {id:'biology',icon:'🧬',name:'Biology',desc:'Life from cells to ecosystems'},
 {id:'math',icon:'∑',name:'Mathematics',desc:'Patterns hiding everywhere'}
];
const lessons=[
 {topic:'science',icon:'⚛️',title:'Quantum Computing',tag:'PHYSICS',concept:'Quantum computers use <em>qubits</em> rather than ordinary bits. A normal bit is 0 or 1; a qubit can be described as a combination of states until it is measured.',example:'Imagine a coin spinning in the air. Before it lands, it is not simply heads or tails. A qubit uses a quantum version of this idea called <b>superposition</b>.',question:'Which property lets a qubit represent a combination of states?',options:['Encryption','Superposition','Compilation','Compression'],answer:1},
 {topic:'technology',icon:'🌐',title:'How the Internet Works',tag:'TECHNOLOGY',concept:'The internet is a huge network of connected computers. When you open a website, your device sends packets of data through routers to a server, which sends information back.',example:'Think of a package delivery system. Your message is split into small packages, each routed through a network and reassembled when they arrive.',question:'What do routers primarily do?',options:['Create websites','Route data between networks','Store passwords','Generate electricity'],answer:1},
 {topic:'psychology',icon:'🧠',title:'The Attention Trap',tag:'PSYCHOLOGY',concept:'Your attention is limited. Switching rapidly between tasks feels productive, but each switch carries a mental cost. Focus improves when you reduce competing signals.',example:'Imagine reading a book while someone keeps tapping your shoulder. You can continue reading, but your brain keeps paying a tiny switching cost.',question:'What does rapid task switching generally add?',options:['More focus','A switching cost','More memory','More sleep'],answer:1},
 {topic:'space',icon:'🌌',title:'Black Holes',tag:'ASTRONOMY',concept:'A black hole is a region of spacetime where gravity is so strong that, past the event horizon, nothing—not even light—can escape to the outside.',example:'Picture a waterfall. Far upstream, you can swim away. Past a certain point near the drop, the current becomes impossible to overcome. That boundary is a rough analogy for an event horizon.',question:'What is the event horizon?',options:['A black hole’s surface','A boundary beyond which escape is impossible','A visible star','The center of a galaxy'],answer:1},
 {topic:'biology',icon:'🧬',title:'DNA',tag:'BIOLOGY',concept:'DNA is a molecule that stores biological instructions. Sections of DNA called genes can provide information used by cells to build proteins and regulate processes.',example:'Think of DNA as a huge library. Genes are like individual recipes, while the cell has machinery that reads and uses those instructions.',question:'What does DNA primarily store?',options:['Heat','Biological information','Electricity','Oxygen'],answer:1}
];

const defaultState={xp:0,lessons:0,streak:0,completed:[],recent:[],lastDay:null};
let state=loadState(); let queue=[...lessons]; let lessonIndex=0; let phase=0; let answered=false; let timer=null;
function loadState(){try{return {...defaultState,...JSON.parse(localStorage.getItem('omu-state')||'{}')}}catch{return {...defaultState}}}
function save(){localStorage.setItem('omu-state',JSON.stringify(state));updateStats()}
function updateStats(){['xpStat','profileXP'].forEach(id=>document.getElementById(id).textContent=state.xp);['streakStat','profileStreak'].forEach(id=>document.getElementById(id).textContent=state.streak);document.getElementById('profileLessons').textContent=state.lessons;const pct=Math.min(100,Math.round((state.completed.length/lessons.length)*100));document.getElementById('progressPercent').textContent=pct+'%';document.getElementById('progressBar').style.width=pct+'%';renderRecent();updateJourney()}
function renderTopics(){document.getElementById('topicGrid').innerHTML=topics.map(t=>`<button class="topic-card" data-topic="${t.id}"><div class="topic-icon">${t.icon}</div><h3>${t.name}</h3><p>${t.desc}</p></button>`).join('');document.querySelectorAll('.topic-card').forEach(b=>b.onclick=()=>startTopic(b.dataset.topic))}
function renderRecent(){const el=document.getElementById('recentList');if(!state.recent.length){el.innerHTML='<div class="recent-item"><span>No lessons yet.</span><b>Start learning →</b></div>';return}el.innerHTML=state.recent.slice(0,6).map(x=>`<div class="recent-item"><b>${x.icon} ${x.title}</b><span>+${x.xp} XP</span></div>`).join('')}
function updateJourney(){const title=document.getElementById('journeyTitle'),text=document.getElementById('journeyText');if(state.lessons){title.textContent='Keep your streak alive.';text.textContent=`You've learned ${state.lessons} topic${state.lessons===1?'':'s'}. Your next minute is waiting.`}}
function showView(id){document.querySelectorAll('main>section').forEach(s=>s.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.nav===id));window.scrollTo({top:0,behavior:'smooth'})}
function startTopic(topic){queue=lessons.filter(l=>l.topic===topic);if(!queue.length)queue=[...lessons];openLesson()}
function startLearning(){queue=[...lessons].sort(()=>Math.random()-.5);openLesson()}
function openLesson(){lessonIndex=0;phase=0;answered=false;document.getElementById('lessonOverlay').classList.remove('hidden');document.body.style.overflow='hidden';renderLesson()}
function renderLesson(){clearInterval(timer);const l=queue[lessonIndex%queue.length];document.getElementById('lessonCount').textContent=`${lessonIndex+1} / ${queue.length}`;document.getElementById('lessonProgress').style.width=((lessonIndex)/queue.length*100)+'%';const c=document.getElementById('lessonContent');if(phase===0){c.innerHTML=`<span class="lesson-kicker">${l.tag} · 30 SEC</span><h2>${l.icon} ${l.title}</h2><p>${l.concept}</p>`;setTimer(30,'30 sec')}else if(phase===1){c.innerHTML=`<span class="lesson-kicker">MAKE IT CLICK · 20 SEC</span><h2>Think of it <em>like this.</em></h2><div class="example-box"><strong>REAL-WORLD EXAMPLE</strong><div>${l.example}</div></div>`;setTimer(20,'20 sec')}else{c.innerHTML=`<span class="lesson-kicker">RECALL · 10 SEC</span><h2>Quick <em>test.</em></h2><p>${l.question}</p><div class="quiz-options">${l.options.map((o,i)=>`<button class="quiz-option" data-i="${i}">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div>`;document.querySelectorAll('.quiz-option').forEach(b=>b.onclick=()=>answer(Number(b.dataset.i)));document.getElementById('timerLabel').textContent='10 sec'}document.getElementById('lessonNext').textContent=phase<2?'Continue →':'Next topic →';document.getElementById('lessonNext').disabled=false}
function setTimer(seconds,label){let left=seconds;document.getElementById('timerLabel').textContent=label;timer=setInterval(()=>{left--;document.getElementById('timerLabel').textContent=left+' sec';if(left<=0){clearInterval(timer);advancePhase()}},1000)}
function advancePhase(){if(phase<2){phase++;renderLesson()}else nextLesson()}
function answer(i){if(answered)return;answered=true;clearInterval(timer);const l=queue[lessonIndex%queue.length];const buttons=document.querySelectorAll('.quiz-option');buttons.forEach((b,n)=>{if(n===l.answer)b.classList.add('correct');if(n===i&&i!==l.answer)b.classList.add('wrong')});if(i===l.answer){state.xp+=10;showToast('+10 XP · Correct!')}else showToast('Keep going — review it later.');completeLesson(l,i===l.answer);document.getElementById('lessonNext').textContent='Next topic →'}
function completeLesson(l,correct){if(!state.completed.includes(l.title)){state.completed.push(l.title);state.lessons++;if(correct)state.xp+=0;state.streak=state.streak||1;state.recent.unshift({title:l.title,icon:l.icon,xp:correct?10:0});state.recent=state.recent.slice(0,10);save()}}
function nextLesson(){lessonIndex++;phase=0;answered=false;if(lessonIndex>=queue.length)queue=[...lessons].sort(()=>Math.random()-.5);renderLesson()}
function closeLesson(){clearInterval(timer);document.getElementById('lessonOverlay').classList.add('hidden');document.body.style.overflow='';updateStats()}
function showToast(text){const t=document.getElementById('toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}

document.getElementById('startBtn').onclick=startLearning;document.getElementById('continueBtn').onclick=startLearning;document.getElementById('exploreBtn').onclick=()=>document.getElementById('topicsView').scrollIntoView({behavior:'smooth'});document.getElementById('allTopicsBtn').onclick=()=>document.getElementById('topicsView').scrollIntoView({behavior:'smooth'});document.getElementById('closeLesson').onclick=closeLesson;document.getElementById('lessonNext').onclick=advancePhase;document.getElementById('profileBtn').onclick=()=>showView('profileView');document.getElementById('profileBack').onclick=()=>showView('homeView');document.getElementById('homeBtn').onclick=()=>showView('homeView');document.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>showView(n.dataset.nav));document.getElementById('searchBtn').onclick=()=>showToast('Search is coming in the next version.');
renderTopics();updateStats();
